name: CI/CD Publish npm Package

on:
  push:
    tags:
      - "v*"

  workflow_dispatch:

jobs:
  build-test-publish:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 22
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Build package
        run: npm run build

      - name: Verify package
        run: npm pack --dry-run

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Extract Tag Message
        id: tag_message
        run: |
          git fetch --tags --force
          TAG_MSG=$(git tag -l --format='%(contents)' ${{ github.ref_name }})
          echo "tag_msg<<EOF" >> $GITHUB_OUTPUT
          echo "$TAG_MSG" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          body: ${{ steps.tag_message.outputs.tag_msg }}
          generate_release_notes: true

  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 22
          registry-url: "https://npm.pkg.github.com"
          scope: "@yearningss"

      - name: Install dependencies
        run: npm ci

      - name: Build package
        run: npm run build

      - name: Scope package name for GitHub Packages
        run: node -e "const fs = require('fs'); const pkg = JSON.parse(fs.readFileSync('./package.json', 'utf8')); pkg.name = '@yearningss/' + pkg.name.toLowerCase(); fs.writeFileSync('./package.json', JSON.stringify(pkg, null, 2), 'utf8');"

      - name: Publish to GitHub Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
